# omarchy-robominds-theme

# Main bg
theme[main_bg]="#1D2730"

# Main text color
theme[main_fg]="#E6E6E6"

# Title color for boxes
theme[title]="#E6E6E6"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#E86850"

# Background color of selected item in processes box
theme[selected_bg]="#364450"

# Foreground color of selected item in processes box
theme[selected_fg]="#FFC000"

# Color of inactive/disabled text
theme[inactive_fg]="#364450"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#00E0CA"

# Cpu box outline color
theme[cpu_box]="#364450"

# Memory/disks box outline color
theme[mem_box]="#364450"

# Net up/down box outline color
theme[net_box]="#364450"

# Processes box outline color
theme[proc_box]="#364450"

# Box divider line and small boxes line color
theme[div_line]="#364450"

# Temperature graph colors
theme[temp_start]="#33E6D2"
theme[temp_mid]="#FFD040"
theme[temp_end]="#E86850"

# CPU graph colors
theme[cpu_start]="#33E6D2"
theme[cpu_mid]="#FFD040"
theme[cpu_end]="#E86850"

# Mem/Disk free meter
theme[free_start]="#E86850"
theme[free_mid]="#FF9E50"
theme[free_end]="#FFC000"

# Mem/Disk cached meter
theme[cached_start]="#FFC000"
theme[cached_mid]="#FFD040"
theme[cached_end]="#FF9E50"

# Mem/Disk available meter
theme[available_start]="#00E0CA"
theme[available_mid]="#33E6D2"
theme[available_end]="#00E0EA"

# Mem/Disk used meter
theme[used_start]="#00B8D0"
theme[used_mid]="#00E0CA"
theme[used_end]="#33E6F0"

# Download graph colors
theme[download_start]="#00E0CA"
theme[download_mid]="#33E6D2"
theme[download_end]="#00E0EA"

# Upload graph colors
theme[upload_start]="#FFD040"
theme[upload_mid]="#FFC000"
theme[upload_end]="#E86850"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#33E6D2"
theme[process_mid]="#FFD040"
theme[process_end]="#E86850"
