mode = "dark"

accent = "#0052BB"
selection = "#1D2731"
muted = "#3C3C3C"
background = "#1D2731"
dark_background = "#0E0E13"
darker_background = "#0A0A0A"
lighter_background = "#262626"
foreground = "#E6E6E6"
dark_foreground = "#BBBBBB"
light_foreground = "#F2F2F2"
bright_foreground = "#FFFFFF"
red = "#D32F2F"
yellow = "#E8A100"
orange = "#E4761B"
green = "#15803D"
cyan = "#12857F"
blue = "#0052BB"
magenta = "#6D46B8"
brown = "#A34F0E"
bright_red = "#E88585"
bright_yellow = "#F4C64D"
bright_green = "#6FC08D"
bright_cyan = "#66BDB6"
bright_blue = "#0073D7"
bright_magenta = "#A98BE0"
