#!/usr/bin/env python3
"""CLI interface for palettgen."""

import argparse
import sys
from pathlib import Path

from palettgen.palette import generate_palette


def main():
    parser = argparse.ArgumentParser(
        description="Generate perceptually uniform terminal color palettes from brand colors"
    )
    parser.add_argument(
        "--brand",
        required=True,
        help="Brand color in hex format (e.g., #0052BB)"
    )
    parser.add_argument(
        "--mode",
        choices=["dark", "light"],
        default="dark",
        help="Color mode (default: dark)"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("colors.toml"),
        help="Output file path (default: colors.toml)"
    )
    
    args = parser.parse_args()
    
    # Generate palette
    palette = generate_palette(args.brand, args.mode)
    
    # Write TOML file
    with open(args.output, "w") as f:
        f.write("# Generated by palettgen\n")
        f.write(f"# Brand color: {args.brand}\n")
        f.write(f"# Mode: {args.mode}\n\n")
        
        for key, value in palette.items():
            f.write(f'{key} = "{value}"\n')
    
    print(f"✓ Generated {args.output} ({args.mode} mode, {len(palette)} colors)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
