#!/usr/bin/env python3
"""CLI interface for palettgen.

Default behaviour (no ``--mode``) generates everything from a single
brand color: both dark and light TOML files, both palette PNG images,
and the README image references.

    python -m palettgen.cli --brand "#0052BB"

To generate a single mode only, pass ``--mode dark`` or ``--mode light``::

    python -m palettgen.cli --brand "#0052BB" --mode dark --output colors.toml
"""

import argparse
import sys
from pathlib import Path

from palettgen.palette import generate_palette


def _write_toml(palette: dict, output: Path, brand: str, mode: str) -> None:
    """Write a palette dict to a TOML file with a header comment."""
    with open(output, "w") as f:
        f.write("# Generated by palettgen\n")
        f.write(f"# Brand color: {brand}\n")
        f.write(f"# Mode: {mode}\n\n")
        for key, value in palette.items():
            f.write(f'{key} = "{value}"\n')
    print(f"✓ Generated {output} ({mode} mode, {len(palette)} colors)")


def _run_single_mode(args) -> int:
    """Generate a single mode TOML only."""
    palette = generate_palette(args.brand, args.mode)
    _write_toml(palette, args.output, args.brand, args.mode)
    return 0


def _run_full_update(args) -> int:
    """Generate both modes: TOMLs, images, and README image references."""
    # Derive light output path from the dark one: colors.toml -> colors-light.toml
    dark_output = args.output
    light_output = dark_output.with_name(
        dark_output.stem + "-light" + dark_output.suffix
    )

    # Generate both palettes
    dark_palette = generate_palette(args.brand, "dark")
    light_palette = generate_palette(args.brand, "light")

    _write_toml(dark_palette, dark_output, args.brand, "dark")
    _write_toml(light_palette, light_output, args.brand, "light")

    # Update README images only if README exists
    readme_path = args.readme
    if not readme_path.is_file():
        print(f"Warning: {readme_path} not found, skipping README + image update")
        return 0

    # Generate images and update README with image references
    try:
        from palettgen._images import generate_images

        generate_images(
            dark_toml=dark_output,
            light_toml=light_output,
            images_dir=args.images_dir,
            readme_path=readme_path,
        )
    except ImportError as e:
        print(f"Warning: {e} — skipping image generation", file=sys.stderr)

    return 0


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Generate perceptually uniform terminal color palettes from brand "
            "colors. Without --mode, generates both dark and light palettes, "
            "palette images, and updates the README."
        )
    )
    parser.add_argument(
        "--brand",
        required=True,
        help="Brand color in hex format (e.g., #0052BB)",
    )
    parser.add_argument(
        "--mode",
        choices=["dark", "light"],
        default=None,
        help=(
            "Color mode — generate only this mode. If omitted, generates both "
            "dark and light, palette images, and updates the README (default: "
            "both)."
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("colors.toml"),
        help=(
            "Output file path for dark mode (default: colors.toml). Light mode "
            "is written to <stem>-light.toml."
        ),
    )
    parser.add_argument(
        "--readme",
        type=Path,
        default=Path("README.md"),
        help="Path to README.md (default: README.md)",
    )
    parser.add_argument(
        "--images-dir",
        type=Path,
        default=Path("images"),
        help="Directory for palette PNG images (default: images)",
    )

    args = parser.parse_args()

    if args.mode is not None:
        return _run_single_mode(args)
    return _run_full_update(args)


if __name__ == "__main__":
    sys.exit(main())
